image:
  - Visual Studio 2019
  
configuration:
  - Debug
  - Release
  
install:  
  - git submodule update --init --recursive
  
before_build:
- cmd: cmake -H. -B./.build
  
build:
  verbosity: normal