image:
  - Visual Studio 2019
  
platform:
  - x64
  
configuration:
  - Release
  
install:  
  - git submodule update --init --recursive
  
before_build:
- cmd: cmake -H. -B./.build -DCMAKE_INSTALL_PREFIX=./package
  
build:
  publish_nuget: true
  verbosity: normal
  project: .build/INSTALL.vcxproj
  
after_test:
  - cmd: nuget pack -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'